services:
  - type: web
    name: telegrambot
    env: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: python main.py
    pythonVersion: 3.11.8
